name: push-workflow 5
on: push # push 이벤트에의해 workflow를 트리거 하겠다.

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
    - name: step2
      run: |
        echo hello world
        echo gihub action



