name: artifact
on: push

jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo hello-world > hello.txt
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact-test
        path: ./hello.txt

  download_artifact:
    runs-on: ubuntu-latest
    needs: [upload_artifact]
    steps:
    - name: download artifact
      uses: actions/download-artifact@v4
      with:
        name: artifact-test
        path: ./
    - name: check
      run: cat hello.txt

