name: issue-alarm
on:
  issues:
    types: [opened]

jobs:
  issue-normal:
    if: contains(github.event.issue.title, 'normal')
    runs-on: ubuntu-latest
    steps:
    - name: echo alarm
      id: normal-title
      run: echo "title=${{ github.event.issue.title }}" >> $GITHUB_OUTPUT
    - name: Send Slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: ${{ toJSON({
          attachments: [
            {
              pretext: "issue create",
              color: "28a745",
              fields: [
                {
                  title: "normal issue create",
                  short: true,
                  value: steps.normal-title.outputs.title
                }
              ]
            }
          ]
        }) }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK