name: path-filter
on:
  push:
    paths:
    - '.github/workflows/part1/*'
    - '!.github/workflows/part1/push.yaml'

jobs:
  path_filter:
    runs-on: ubuntu-latest
    steps:
    - name: echo name
      run: echo hello